### ISSUE TITLE
Poor Performance on Ryzen Platform

### ISSUE THREAD

**Issue by WiggyWire** [Kautenja/RackNES#41] opened 2020-07-08 12:27 UTC
Running a pacman rom gives 31% on a ryzen 2200g with 8gigs of ram. Some optimization needed.

**Comment by Kautenja** [comment] 2020-07-08 18:24
More or less a duplicate of #9. RAM has nothing to do with this, the NES had KB of RAM. Emulation inside VCV Rack is just a compute intensive process. This is not a bug, but an inherent and intentional design flaw. For each audio sample, many NES CPU clock cycles have to run.

**Closed as completed by Kautenja** 2020-07-08 18:24 UTC
Labels: duplicate, wontfix

**Comment by Kautenja** [comment] 2020-07-08 18:41
In response to this issue, I've located two areas that I believe to be non-performant (plz see reference links above), and will see how addressing these issues improves performance. However, my original statement still stands in that CPU emulation is compute intensive. I'm not sure if these changes will produce much measurable effect.
